apiVersion: rbac.authorization.k8s.io/v1
kind: ClusterRole
metadata:
  name: elastic-operator
rules:
- apiGroups:
  - "authorization.k8s.io"
  resources:
  - subjectaccessreviews
  verbs:
  - create
- apiGroups:
  - ""
  resources:
  - pods
  - endpoints
  - events
  - persistentvolumeclaims
  - secrets
  - services
  - configmaps
  verbs:
  - get
  - list
  - watch
  - create
  - update
  - patch
  - delete
- apiGroups:
  - apps
  resources:
  - deployments
  - statefulsets
  verbs:
  - get
  - list
  - watch
  - create
  - update
  - patch
  - delete
- apiGroups:
  - policy
  resources:
  - poddisruptionbudgets
  verbs:
  - get
  - list
  - watch
  - create
  - update
  - patch
  - delete
- apiGroups:
  - elasticsearch.k8s.elastic.co
  resources:
  - elasticsearches
  - elasticsearches/status
  - elasticsearches/finalizers
  - enterpriselicenses
  - enterpriselicenses/status
  verbs:
  - get
  - list
  - watch
  - create
  - update
  - patch
  - delete
- apiGroups:
  - kibana.k8s.elastic.co
  resources:
  - kibanas
  - kibanas/status
  - kibanas/finalizers
  verbs:
  - get
  - list
  - watch
  - create
  - update
  - patch
  - delete
- apiGroups:
  - apm.k8s.elastic.co
  resources:
  - apmservers
  - apmservers/status
  - apmservers/finalizers
  verbs:
  - get
  - list
  - watch
  - create
  - update
  - patch
  - delete
- apiGroups:
  - admissionregistration.k8s.io
  resources:
  - mutatingwebhookconfigurations
  - validatingwebhookconfigurations
  verbs:
  - get
  - list
  - watch
  - create
  - update
  - patch
  - delete

---
apiVersion: rbac.authorization.k8s.io/v1
kind: ClusterRoleBinding
metadata:
  name: elastic-operator
roleRef:
  apiGroup: rbac.authorization.k8s.io
  kind: ClusterRole
  name: elastic-operator
subjects:
- kind: ServiceAccount
  name: elastic-operator
  namespace: elastic-system

---
apiVersion: v1
kind: Namespace
metadata:
  name: elastic-system

---
apiVersion: apps/v1
kind: StatefulSet
metadata:
  name: elastic-operator
  namespace: elastic-system
  labels:
    control-plane: elastic-operator
spec:
  selector:
    matchLabels:
      control-plane: elastic-operator
  serviceName: elastic-operator
  template:
    metadata:
      annotations:
        "co.elastic.logs/raw": "[{\"type\":\"container\",\"json.keys_under_root\":true,\"paths\":[\"/var/log/containers/*${data.kubernetes.container.id}.log\"],\"processors\":[{\"convert\":{\"mode\":\"rename\",\"ignore_missing\":true,\"fields\":[{\"from\":\"error\",\"to\":\"_error\"}]}},{\"convert\":{\"mode\":\"rename\",\"ignore_missing\":true,\"fields\":[{\"from\":\"_error\",\"to\":\"error.message\"}]}},{\"convert\":{\"mode\":\"rename\",\"ignore_missing\":true,\"fields\":[{\"from\":\"source\",\"to\":\"_source\"}]}},{\"convert\":{\"mode\":\"rename\",\"ignore_missing\":true,\"fields\":[{\"from\":\"_source\",\"to\":\"event.source\"}]}}]}]"
      labels:
        control-plane: elastic-operator
    spec:
      serviceAccountName: elastic-operator
      containers:
      - image: docker.elastic.co/eck/eck-operator:2.4.0
        name: manager
        args: ["manager", "--enable-webhook", "--log-verbosity=0"]
        env:
          - name: OPERATOR_NAMESPACE
            valueFrom:
              fieldRef:
                fieldPath: metadata.namespace
          - name: WEBHOOK_SECRET
            value: elastic-webhook-server-cert
          - name: OPERATOR_IMAGE
            value: docker.elastic.co/eck/eck-operator:2.4.0
        resources:
          limits:
            cpu: 1
            memory: 512Mi
          requests:
            cpu: 100m
            memory: 150Mi
        ports:
        - containerPort: 9443
          name: webhook-server
          protocol: TCP
        volumeMounts:
          - mountPath: /tmp/k8s-webhook-server/serving-certs
            name: cert
            readOnly: true
      terminationGracePeriodSeconds: 10
      volumes:
        - name: cert
          secret:
            defaultMode: 420
            secretName: elastic-webhook-server-cert

---
apiVersion: rbac.authorization.k8s.io/v1
kind: ClusterRole
metadata:
  name: elastic-operator-view
  labels:
    rbac.authorization.k8s.io/aggregate-to-view: "true"
    rbac.authorization.k8s.io/aggregate-to-edit: "true"
    rbac.authorization.k8s.io/aggregate-to-admin: "true"
rules:
  - apiGroups: ["elasticsearch.k8s.elastic.co"]
    resources: ["elasticsearches"]
    verbs: ["get", "list", "watch"]
  - apiGroups: ["apm.k8s.elastic.co"]
    resources: ["apmservers"]
    verbs: ["get", "list", "watch"]
  - apiGroups: ["kibana.k8s.elastic.co"]
    resources: ["kibanas"]
    verbs: ["get", "list", "watch"]

---

apiVersion: rbac.authorization.k8s.io/v1
kind: ClusterRole
metadata:
  name: elastic-operator-edit
  labels:
    rbac.authorization.k8s.io/aggregate-to-edit: "true"
    rbac.authorization.k8s.io/aggregate-to-admin: "true"
rules:
  - apiGroups: ["elasticsearch.k8s.elastic.co"]
    resources: ["elasticsearches"]
    verbs: ["create", "delete", "deletecollection", "patch", "update"]
  - apiGroups: ["apm.k8s.elastic.co"]
    resources: ["apmservers"]
    verbs: ["create", "delete", "deletecollection", "patch", "update"]
  - apiGroups: ["kibana.k8s.elastic.co"]
    resources: ["kibanas"]
    verbs: ["create", "delete", "deletecollection", "patch", "update"]

---
apiVersion: v1
kind: ServiceAccount
metadata:
  name: elastic-operator
  namespace: elastic-system

---
# apiVersion: admissionregistration.k8s.io/v1beta1
# kind: ValidatingWebhookConfiguration
# metadata:
#   creationTimestamp: null
#   name: elastic-webhook.k8s.elastic.co
# webhooks:
# - clientConfig:
#     caBundle: Cg==
#     service:
#       name: elastic-webhook-server
#       namespace: elastic-system
#       path: /validate-apm-k8s-elastic-co-v1-apmserver
#   failurePolicy: Ignore
#   name: elastic-apm-validation-v1.k8s.elastic.co
#   rules:
#   - apiGroups:
#     - apm.k8s.elastic.co
#     apiVersions:
#     - v1
#     operations:
#     - CREATE
#     - UPDATE
#     resources:
#     - apmservers
# - clientConfig:
#     caBundle: Cg==
#     service:
#       name: elastic-webhook-server
#       namespace: elastic-system
#       path: /validate-apm-k8s-elastic-co-v1beta1-apmserver
#   failurePolicy: Ignore
#   name: elastic-apm-validation-v1beta1.k8s.elastic.co
#   rules:
#   - apiGroups:
#     - apm.k8s.elastic.co
#     apiVersions:
#     - v1beta1
#     operations:
#     - CREATE
#     - UPDATE
#     resources:
#     - apmservers
# - clientConfig:
#     caBundle: Cg==
#     service:
#       name: elastic-webhook-server
#       namespace: elastic-system
#       path: /validate-elasticsearch-k8s-elastic-co-v1-elasticsearch
#   failurePolicy: Ignore
#   name: elastic-es-validation-v1.k8s.elastic.co
#   rules:
#   - apiGroups:
#     - elasticsearch.k8s.elastic.co
#     apiVersions:
#     - v1
#     operations:
#     - CREATE
#     - UPDATE
#     resources:
#     - elasticsearches
# - clientConfig:
#     caBundle: Cg==
#     service:
#       name: elastic-webhook-server
#       namespace: elastic-system
#       path: /validate-elasticsearch-k8s-elastic-co-v1beta1-elasticsearch
#   failurePolicy: Ignore
#   name: elastic-es-validation-v1beta1.k8s.elastic.co
#   rules:
#   - apiGroups:
#     - elasticsearch.k8s.elastic.co
#     apiVersions:
#     - v1beta1
#     operations:
#     - CREATE
#     - UPDATE
#     resources:
#     - elasticsearches
# - clientConfig:
#     caBundle: Cg==
#     service:
#       name: elastic-webhook-server
#       namespace: elastic-system
#       path: /validate-kibana-k8s-elastic-co-v1-kibana
#   failurePolicy: Ignore
#   name: elastic-kb-validation-v1.k8s.elastic.co
#   rules:
#   - apiGroups:
#     - kibana.k8s.elastic.co
#     apiVersions:
#     - v1
#     operations:
#     - CREATE
#     - UPDATE
#     resources:
#     - kibanas
# - clientConfig:
#     caBundle: Cg==
#     service:
#       name: elastic-webhook-server
#       namespace: elastic-system
#       path: /validate-kibana-k8s-elastic-co-v1beta1-kibana
#   failurePolicy: Ignore
#   name: elastic-kb-validation-v1beta1.k8s.elastic.co
#   rules:
#   - apiGroups:
#     - kibana.k8s.elastic.co
#     apiVersions:
#     - v1beta1
#     operations:
#     - CREATE
#     - UPDATE
#     resources:
#     - kibanas
# ---
# apiVersion: v1
# kind: Service
# metadata:
#   name: elastic-webhook-server
#   namespace: elastic-system
# spec:
#   ports:
#     - port: 443
#       targetPort: 9443
#   selector:
#     control-plane: elastic-operator
# ---
# apiVersion: v1
# kind: Secret
# metadata:
#   name: elastic-webhook-server-cert
#   namespace: elastic-system
