apiVersion: elasticsearch.k8s.elastic.co/v1
kind: Elasticsearch
metadata:
  name: elasticsearch
  namespace: elastic-system
spec:
  version: 8.4.0
  auth:
    fileRealm:
      - secretName: my-file-realm-secret
  http:
    tls:
      selfSignedCertificate:
        disabled: true
  nodeSets:
  - name: master-nodes
    count: 3
    config:
      node.roles: ["data", "ingest", "master"]    
      #node.master: true
      #node.data: true
      #node.ingest: false
      #xpack.ml.enabled: true
      #xpack.security.http.ssl.enabled: false
      #xpack.security.transport.ssl.enabled: false
      #xpack.security.enabled: false
    podTemplate:
      spec:
        tolerations:
          - key: "special"
            operator: "Exists"
            effect: "NoSchedule"
        initContainers:
        - name: sysctl
          securityContext:
            privileged: true
          command: ['sh', '-c', 'sysctl -w vm.max_map_count=262144']
        - name: install-plugins
          command:
          - sh
          - -c
          - |
            bin/elasticsearch-plugin install --batch repository-s3
        containers:
        - name: elasticsearch
          env:
          - name: READINESS_PROBE_TIMEOUT
            value: "30"	  
          - name: ES_JAVA_OPTS
            value: "-Xms15g -Xmx15g"
          resources:
            requests:
              memory: 15Gi
              cpu: 1
            limits:
              memory: 20Gi
              cpu: 2
          ports:
          - containerPort: 9200
            name: rest
            protocol: TCP
          - containerPort: 9300
            name: inter-node
            protocol: TCP	      
          #livenessProbe:
          #  initialDelaySeconds: 300
          #  timeoutSeconds: 300
            #periodSeconds: 300
          readinessProbe:
            exec:
              command:
              - bash
              - -c
              - /mnt/elastic-internal/scripts/readiness-probe-script.sh	  
            failureThreshold: 3
            successThreshold: 1
            initialDelaySeconds: 30
            timeoutSeconds: 30
            periodSeconds: 30
        nodeSelector:
          node: elastic
    volumeClaimTemplates:
    - metadata:
        name: elasticsearch-data
      spec:
        accessModes:
        - ReadWriteOnce
        resources:
          requests:
            storage: 100Gi

  # - name: data-nodes
  #   count: 1
  #   config:
  #     node.master: true
  #     node.data: true
  #     node.ingest: true
  #     xpack.ml.enabled: true
  #   podTemplate:
  #     spec:
  #       initContainers:
  #         - name: sysctl
  #           securityContext:
  #             privileged: true
  #           command: ['sh', '-c', 'sysctl -w vm.max_map_count=262144']
  #         - name: install-plugins
  #           command:
  #             - sh
  #             - -c
  #             - |
  #               bin/elasticsearch-plugin install --batch repository-s3
  #       containers:
  #         - name: elasticsearch
  #           env:
  #             - name: ES_JAVA_OPTS
  #               value: "-Xms15g -Xmx15g"
  #           resources:
  #             requests:
  #               memory: 15Gi
  #               cpu: 2
  #             limits:
  #               memory: 15Gi
  #               cpu: 2
  #       nodeSelector:
  #         node: elastic
  #   volumeClaimTemplates:
  #     - metadata:
  #         name: elasticsearch-data
  #       spec:
  #         accessModes:
  #           - ReadWriteOnce
  #         resources:
  #           requests:
  #             storage: 100Gi
  # http:
  #   tls:
  #     selfSignedCertificate:
  #       disabled: true
