apiVersion: elasticsearch.k8s.elastic.co/v1
kind: Elasticsearch
metadata:
  name: elasticsearch
  namespace: elastic-system
spec:
  version: 8.4.1
  nodeSets:
  - name: master-nodes
    count: 3
    config:
      node.store.allow_mmap: false