kind: Service
apiVersion: v1
metadata:
  name: neo4j-ext-lb
  namespace: neo4j
  labels:
    app.kubernetes.io/name: neo4j
    app.kubernetes.io/part-of: neo4j
  annotations:
    # by default the type is external network-facing
    #service.beta.kubernetes.io/aws-load-balancer-internal: 'true'
    # by default the type is elb (classic load balancer).
    service.beta.kubernetes.io/aws-load-balancer-type: nlb
spec:
  # this setting is to make sure the source IP address is preserved.
  #externalTrafficPolicy: Local
  externalTrafficPolicy: Cluster
  type: LoadBalancer
  selector:
    app: neo4j
    #app.kubernetes.io/name: neo4j
    #app.kubernetes.io/part-of: neo4j
  ports:
    - name: http
      port: 7474
      targetPort: 7474
    - name: bolt
      port: 7687
      targetPort: 7687

